### ISSUE TITLE
KModal often displays a vertical scrollbar when used with KCircularLoader, even when there is enough space in the modal/on a page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#210]
## Product

Studio, Design System

## Expected behavior

`KModal` never displays a vertical scrollbar when used with `KCircularLoader` and when there is enough space in the modal/on a page.

## Actual behavior

`KModal` often displays a vertical scrollbar when used with `KCircularLoader`, even when there is enough space in the modal/on a page.

**This screenshot was taken in my Storybook in Chrome where I checked this problem in isolation for the following code** ([you can see the Storybook bundle uploaded here](https://frosty-leakey-98684a.netlify.app/?path=/story/kmodal--with-loader)):
```
<KModal title="Title"><KCircularLoader/></KModal>
```

![modal-loader](https://user-images.githubusercontent.com/13509191/113250200-5c9b7480-92c0-11eb-9fcb-c87e841dc8ef.png)

**This seems to be the primary cause of an issue with vertical bar appearing and disappearing when moving a mouse cursor in Studio:**

There may be another problem, but the vertical scrollbar shouldn't be rendered at all in the first place.

![Peek 2021-03-30 10-02](https://user-images.githubusercontent.com/13509191/113249797-a20b7200-92bf-11eb-8fa1-f8e08074ea50.gif)

## Steps to reproduce the issue

1. Use `KCircularLoader` in the content area of `KModal` (it occasionally happened to me I needed to reload the page to reproduce the bug)

## Additional information

Initial investigation shows that this may be caused by inaccurate calculation in [`updateContentSectionStyle`](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L244).

When the modal is rendered for the first time, [`contentHeight` is updated](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L247). That triggers the` update` lifecycle hook, which causes `updateContentSectionStyle` to be called again - but in this second run, the content area's `scrollHeight` is a couple of pixels larger than its `clientHeight` (usually it's 2 or 3 pixels though the value may vary) which [causes the scrollbar to be displayed](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L266). I am not sure why `scrollHeight` slightly differs from `clientHeight` - I suspect it may have something to do with the loader overflow.

## Environment
- OS: Ubuntu
- Browser version: Chrome, Firefox

**Comment by MisRob** [comment]
I am wondering if using a threshold value [in this condition ](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L266) might help, similarly to how we use it for example [here](https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L246). We would need to be careful though and check that those content areas that are close to the accepted range won't get cut because of the threshold (maybe we could increase the content section height by the chosen threshold value to be sure that the content fits all the time)

**Comment by MisRob** [comment]
This was recently observed in Kolibri > Device by @rtibbles 

[Screencast from 10-12-2023 04 05 17 PM.webm](https://github.com/learningequality/kolibri-design-system/assets/13509191/4187f118-dfc9-45f7-b41d-feeffd309670)

**Comment by nucleogenesis** [comment]
Per @AlexVelezLl this should be retested using KDS `develop` branch

**Comment by nucleogenesis** [comment]
@pcenov @radinamatic this should be replicatable by opening the Select Device modal using Slow/Fast 3G network throttling.

**Comment by AlexVelezLl** [comment]
This is something that could have been fixed in https://github.com/learningequality/kolibri-design-system/pull/590, you can test this change in Kolibri with the artifacts of this [PR](https://github.com/learningequality/kolibri/pull/12209).

One place where I have noted that always appears this vertical scrollbar is in the setup wizard with English language, setting up an LOD device and importing users as admin:
![image](https://github.com/learningequality/kolibri-design-system/assets/51239030/054c3013-5bf3-4671-bb56-c582ef22e68c)

**Comment by pcenov** [comment]
Hi @AlexVelezLl - I confirm that the issue with the unnecessary scrollbar is still present when using the artifacts from this [PR](https://github.com/learningequality/kolibri/pull/12209).

**Comment by karankoder** [comment]
Hi @MisRob, i want to work on this issue.

**Comment by AlexVelezLl** [comment]
Hey @karankoder! I will assign this to you. Please, let us know if you have any questions.

An easy way to replicate this, is to test this in the playground:

```Vue
<KModal title="Title"><KCircularLoader/></KModal>
```

**Comment by karankoder** [comment]
Thank you for assigning this to me! I’ll start working on it and will let you know if I have any questions or need clarification.

**Comment by karankoder** [comment]
@AlexVelezLl i have created a PR, please review.

**Comment by marcellamaki** [comment]
Hi @karankoder - I've added myself and Alex as reviewers to your PR. We will do our best to review it within one week. Thanks for your contribution!
